language: java
install: wget https://github.com/broadinstitute/cromwell/releases/download/34/cromwell-34.jar
script: java -jar cromwell-34.jar run -t cwl -i ./example_data/exome_workflow.yaml ./exome_workflow.cwl
