sudo: required

services: 
    - docker

install: docker pull johnegarza/travis-cromwell

#travis is currently inside the repo to be tested; this should be mounted
#inside the docker container for testing, but the path is determined at runtime,
#so use pwd inside the command to get the full path
script: docker run -v $(pwd) travis-cromwell
